spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://keycloak_postgres:5435/pendientico-core}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: core
    show-sql: true

  flyway:
    schemas: core
    default-schema: core
    baseline-on-migrate: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8092/realms/pendientico

server:
  port: 8082

management:
  metrics:
    export:
      defaults:
        enabled: false


keycloak:
  url: http://localhost:8092
  realm: pendientico
  client-id: pendientico-backend-core
  client-secret: GqJoZsoXLFTTp9Vsb7Fk8Bwx6Uh71qaG
